# Generated by Django 5.0.6 on 2024-06-23 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='createdDate',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='publishedDate',
            new_name='published_date',
        ),
    ]
